# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'
name: yourbrand

services:
  store-web:
    image: store-web
    container_name: store-web
    build:
      context: .
      dockerfile: src/Store/Web/Server/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "yourbrand-catalog-api-url=http://host.docker.internal:8082"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  catalog-api:
    image: catalog-api
    container_name: catalog-api
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8082:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CatalogDb=Server=host.docker.internal,1433;User Id=sa;Password=P@ssw0rd;Encrypt=false;Database=yourbrand-catalog-db
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - "MSSQL_SA_PASSWORD=P@ssw0rd"
      - "MSSQL_PID=Developer"
      - "ACCEPT_EULA=1"
    ports:
      - "1433:1433"
    hostname: mssql
    volumes:
      - "./data/sql-edge:/var/opt/mssql"