x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: Store API
  version: 1.0.0
servers:
- url: https://localhost:7188
paths:
  /api/products:
    get:
      tags:
      - Products
      operationId: Products_GetProducts
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          format: int32
          nullable: true
        x-position: 1
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
          nullable: true
        x-position: 2
      - name: searchTerm
        in: query
        schema:
          type: string
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResultOfProduct'
        404:
          description: ''
  /api/products/{id}:
    get:
      tags:
      - Products
      operationId: Products_GetProductById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: ''
  /api/cart:
    get:
      tags:
      - Cart
      operationId: Cart_GetCart
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        404:
          description: ''
  /api/cart/items:
    post:
      tags:
      - Cart
      operationId: Cart_AddCartItem
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCartItemRequest'
        required: true
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItem'
        404:
          description: ''
  /api/cart/items/{cartItemId}/quantity:
    put:
      tags:
      - Cart
      operationId: Cart_UpdateCartItemQuantity
      parameters:
      - name: cartItemId
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCartItemQuantityRequest'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItem'
        404:
          description: ''
  /api/cart/items/{cartItemId}:
    delete:
      tags:
      - Cart
      operationId: Cart_RemoveCartItem
      parameters:
      - name: cartItemId
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
        404:
          description: ''
  /requires-auth:
    get:
      operationId: GetRequiresAuth
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: string
  /api/weatherforecast:
    get:
      operationId: GetWeatherForecast
      parameters:
      - name: startDate
        in: query
        required: true
        schema:
          type: string
          format: date
        x-position: 1
      responses:
        200:
          description: ''
  /identity/register:
    post:
      operationId: PostIdentityRegister
      requestBody:
        x-name: registration
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        x-position: 1
      responses:
        200:
          description: ''
        400:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
  /identity/login:
    post:
      operationId: PostIdentityLogin
      parameters:
      - name: cookieMode
        in: query
        schema:
          type: boolean
          nullable: true
        x-position: 2
      - name: persistCookies
        in: query
        schema:
          type: boolean
          nullable: true
        x-position: 3
      requestBody:
        x-name: login
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
  /identity/refresh:
    post:
      operationId: PostIdentityRefresh
      requestBody:
        x-name: refreshRequest
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
  /identity/confirmEmail:
    get:
      operationId: MapIdentityApi-/identity/confirmEmail
      parameters:
      - name: userId
        in: query
        schema:
          type: string
        x-position: 1
      - name: code
        in: query
        schema:
          type: string
        x-position: 2
      - name: changedEmail
        in: query
        schema:
          type: string
        x-position: 3
      responses:
        200:
          description: ''
  /identity/resendConfirmationEmail:
    post:
      operationId: PostIdentityResendConfirmationEmail
      requestBody:
        x-name: resendRequest
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendEmailRequest'
        x-position: 1
      responses:
        200:
          description: ''
  /identity/resetPassword:
    post:
      operationId: PostIdentityResetPassword
      requestBody:
        x-name: resetRequest
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
        x-position: 1
      responses:
        200:
          description: ''
        400:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
  /identity/account/2fa:
    get:
      operationId: GetIdentityAccount2fa
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TwoFactorResponse'
        404:
          description: ''
    post:
      operationId: PostIdentityAccount2fa
      requestBody:
        x-name: tfaRequest
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TwoFactorRequest'
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TwoFactorResponse'
        400:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
        404:
          description: ''
  /identity/account/info:
    get:
      operationId: GetIdentityAccountInfo
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
        400:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
        404:
          description: ''
    post:
      operationId: PostIdentityAccountInfo
      requestBody:
        x-name: infoRequest
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InfoRequest'
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
        400:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
        404:
          description: ''
components:
  schemas:
    PagedResultOfProduct:
      type: object
      additionalProperties: false
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        total:
          type: integer
          format: int32
    Product:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        image:
          type: string
          nullable: true
        description:
          type: string
        price:
          type: number
          format: decimal
        regularPrice:
          type: number
          format: decimal
          nullable: true
        handle:
          type: string
    Cart:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        name:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
    CartItem:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        name:
          type: string
        image:
          type: string
          nullable: true
        productId:
          type: integer
          format: int64
          nullable: true
        productHandle:
          type: string
          nullable: true
        description:
          type: string
        price:
          type: number
          format: decimal
        regularPrice:
          type: number
          format: decimal
          nullable: true
        quantity:
          type: integer
          format: int32
        total:
          type: number
          format: decimal
    AddCartItemRequest:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        image:
          type: string
          nullable: true
        productId:
          type: integer
          format: int64
          nullable: true
        productHandle:
          type: string
          nullable: true
        description:
          type: string
        price:
          type: number
          format: decimal
        regularPrice:
          type: number
          format: decimal
          nullable: true
        quantity:
          type: integer
          format: int32
    UpdateCartItemQuantityRequest:
      type: object
      additionalProperties: false
      properties:
        quantity:
          type: integer
          format: int32
    HttpValidationProblemDetails:
      allOf:
      - $ref: '#/components/schemas/ProblemDetails'
      - type: object
        additionalProperties:
          nullable: true
        properties:
          errors:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
    ProblemDetails:
      type: object
      additionalProperties:
        nullable: true
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
    RegisterRequest:
      type: object
      additionalProperties: false
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
    AccessTokenResponse:
      type: object
      additionalProperties: false
      properties:
        token_type:
          type: string
        access_token:
          type: string
        expires_in:
          type: integer
          format: int64
        refresh_token:
          type: string
    LoginRequest:
      type: object
      additionalProperties: false
      properties:
        username:
          type: string
        password:
          type: string
        twoFactorCode:
          type: string
          nullable: true
        twoFactorRecoveryCode:
          type: string
          nullable: true
    RefreshRequest:
      type: object
      additionalProperties: false
      properties:
        refreshToken:
          type: string
    ResendEmailRequest:
      type: object
      additionalProperties: false
      properties:
        email:
          type: string
    ResetPasswordRequest:
      type: object
      additionalProperties: false
      properties:
        email:
          type: string
        resetCode:
          type: string
          nullable: true
        newPassword:
          type: string
          nullable: true
    TwoFactorResponse:
      type: object
      additionalProperties: false
      properties:
        sharedKey:
          type: string
        recoveryCodesLeft:
          type: integer
          format: int32
        recoveryCodes:
          type: array
          nullable: true
          items:
            type: string
        isTwoFactorEnabled:
          type: boolean
        isMachineRemembered:
          type: boolean
    TwoFactorRequest:
      type: object
      additionalProperties: false
      properties:
        enable:
          type: boolean
          nullable: true
        twoFactorCode:
          type: string
          nullable: true
        resetSharedKey:
          type: boolean
        resetRecoveryCodes:
          type: boolean
        forgetMachine:
          type: boolean
    InfoResponse:
      type: object
      additionalProperties: false
      properties:
        username:
          type: string
        email:
          type: string
        claims:
          type: object
          additionalProperties:
            type: string
    InfoRequest:
      type: object
      additionalProperties: false
      properties:
        newUsername:
          type: string
          nullable: true
        newEmail:
          type: string
          nullable: true
        newPassword:
          type: string
          nullable: true
        oldPassword:
          type: string
          nullable: true
