global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'store-web'
    static_configs:
      - targets: ['store-web:8080']
  - job_name: 'admin-web'
    static_configs:
      - targets: ['admin-web:8084']
  - job_name: 'catalog-svc'
    static_configs:
      - targets: ['catalog-svc:8082']
  - job_name: 'carts-svc'
    static_configs:
      - targets: ['carts-svc:8083']