global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'store-web'
    static_configs:
      - targets: ['host.docker.internal:5153']
  - job_name: 'admin-web'
    static_configs:
      - targets: ['host.docker.internal:5000']
  - job_name: 'catalog-svc'
    static_configs:
      - targets: ['host.docker.internal:5243']
  - job_name: 'carts-svc'
    static_configs:
      - targets: ['host.docker.internal:5245']