x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v10.0.0.0))
openapi: 3.0.0
info:
  title: Catalog API
  version: 1.0.0
servers:
- url: https://localhost:7134
paths:
  /api/products:
    get:
      tags:
      - Products
      operationId: Products_GetProducts
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          format: int32
        x-position: 1
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
        x-position: 2
      - name: searchTerm
        in: query
        schema:
          type: string
        x-position: 3
      - name: categoryPath
        in: query
        schema:
          type: string
        x-position: 4
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResultOfProduct'
    post:
      tags:
      - Products
      operationId: Products_CreateProduct
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
        required: true
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: ''
  /api/products/{idOrHandle}:
    get:
      tags:
      - Products
      operationId: Products_GetProductById
      parameters:
      - name: idOrHandle
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: ''
    put:
      tags:
      - Products
      operationId: Products_UpdateProductDetails
      parameters:
      - name: idOrHandle
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductDetailsRequest'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
        404:
          description: ''
    delete:
      tags:
      - Products
      operationId: Products_DeleteProduct
      parameters:
      - name: idOrHandle
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
        404:
          description: ''
  /api/products/{idOrHandle}/price:
    put:
      tags:
      - Products
      operationId: Products_UpdateProductPrice
      parameters:
      - name: idOrHandle
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductPriceRequest'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
        404:
          description: ''
  /api/products/{idOrHandle}/image:
    post:
      tags:
      - Products
      operationId: Products_UploadProductImage
      parameters:
      - name: idOrHandle
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: string
        404:
          description: ''
  /api/products/{idOrHandle}/handle:
    put:
      tags:
      - Products
      operationId: Products_UpdateProductHandle
      parameters:
      - name: idOrHandle
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductHandleRequest'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
        404:
          description: ''
  /api/products/{idOrHandle}/category:
    put:
      tags:
      - Products
      operationId: Products_UpdateProductCategory
      parameters:
      - name: idOrHandle
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductCategoryRequest'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
        404:
          description: ''
  /api/productCategories:
    get:
      tags:
      - ProductCategories
      operationId: ProductCategories_GetProductCategories
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          format: int32
        x-position: 1
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
        x-position: 2
      - name: searchTerm
        in: query
        schema:
          type: string
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResultOfProductCategory'
    post:
      tags:
      - ProductCategories
      operationId: ProductCategories_CreateProductCategory
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductCategoryRequest'
        required: true
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCategory'
        400:
          description: ''
  /api/productCategories/tree:
    get:
      tags:
      - ProductCategories
      operationId: ProductCategories_GetProductCategoryTree
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCategoryTreeRootDto'
        400:
          description: ''
  /api/productCategories/{idOrPath}:
    put:
      tags:
      - ProductCategories
      operationId: ProductCategories_UpdateProductCategoryDetails
      parameters:
      - name: idOrPath
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductCategoryDetailsRequest'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
        404:
          description: ''
    delete:
      tags:
      - ProductCategories
      operationId: ProductCategories_DeleteProductCategory
      parameters:
      - name: idOrPath
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
        404:
          description: ''
  /api/ProductCategories/{idOrPath}:
    get:
      tags:
      - ProductCategories
      operationId: ProductCategories_GetProductCategoryById
      parameters:
      - name: idOrPath
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCategory'
components:
  schemas:
    PagedResultOfProduct:
      type: object
      additionalProperties: false
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        total:
          type: integer
          format: int32
    Product:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/ProductCategoryParent'
        description:
          type: string
        price:
          type: number
          format: decimal
        regularPrice:
          type: number
          format: decimal
          nullable: true
        image:
          type: string
          nullable: true
        handle:
          type: string
    ProductCategoryParent:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
          nullable: true
        handle:
          type: string
        path:
          type: string
        parent:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/ProductCategoryParent'
    CreateProductRequest:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        description:
          type: string
        categoryId:
          type: integer
          format: int64
        price:
          type: number
          format: decimal
        handle:
          type: string
    UpdateProductDetailsRequest:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        description:
          type: string
    UpdateProductPriceRequest:
      type: object
      additionalProperties: false
      properties:
        price:
          type: number
          format: decimal
    UpdateProductHandleRequest:
      type: object
      additionalProperties: false
      properties:
        handle:
          type: string
    UpdateProductCategoryRequest:
      type: object
      additionalProperties: false
      properties:
        productCategoryId:
          type: integer
          format: int64
    PagedResultOfProductCategory:
      type: object
      additionalProperties: false
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductCategory'
        total:
          type: integer
          format: int32
    ProductCategory:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
          nullable: true
        parent:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/ProductCategoryParent'
        canAddProducts:
          type: boolean
        productsCount:
          type: integer
          format: int64
        handle:
          type: string
        path:
          type: string
    ProductCategoryTreeRootDto:
      type: object
      additionalProperties: false
      properties:
        categories:
          type: array
          items:
            $ref: '#/components/schemas/ProductCategoryTreeNodeDto'
        productsCount:
          type: integer
          format: int64
    ProductCategoryTreeNodeDto:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        handle:
          type: string
        path:
          type: string
        description:
          type: string
          nullable: true
        parent:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/ParentProductCategoryDto'
        subCategories:
          type: array
          items:
            $ref: '#/components/schemas/ProductCategoryTreeNodeDto'
        productsCount:
          type: integer
          format: int64
        canAddProducts:
          type: boolean
    ParentProductCategoryDto:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        handle:
          type: string
        path:
          type: string
        parent:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/ParentProductCategoryDto'
        productsCount:
          type: integer
          format: int64
    CreateProductCategoryRequest:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: decimal
        path:
          type: string
    UpdateProductCategoryDetailsRequest:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        description:
          type: string
    ProblemDetails:
      type: object
      additionalProperties:
        nullable: true
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
