x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: Admin API
  version: 1.0.0
servers:
- url: https://localhost:5001
paths:
  /api/products:
    get:
      tags:
      - Products
      operationId: Products_GetProducts
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          format: int32
        x-position: 1
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
        x-position: 2
      - name: searchTerm
        in: query
        schema:
          type: string
        x-position: 3
      - name: sortBy
        in: query
        schema:
          type: string
        x-position: 4
      - name: sortDirection
        in: query
        schema:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/SortDirection'
        x-position: 5
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResultOfProduct'
    post:
      tags:
      - Products
      operationId: Products_CreateProduct
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
        required: true
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: ''
  /api/products/{id}:
    get:
      tags:
      - Products
      operationId: Products_GetProductById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: ''
    put:
      tags:
      - Products
      operationId: Products_UpdateProductDetails
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductDetailsRequest'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
        404:
          description: ''
    delete:
      tags:
      - Products
      operationId: Products_DeleteProduct
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
        404:
          description: ''
  /api/products/price:
    put:
      tags:
      - Products
      operationId: Products_UpdateProductPrice
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductPriceRequest'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
        404:
          description: ''
  /api/products/handle:
    put:
      tags:
      - Products
      operationId: Products_UpdateProductHandle
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductHandleRequest'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
        404:
          description: ''
  /api/products/category:
    put:
      tags:
      - Products
      operationId: Products_UpdateProductCategory
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductCategoryRequest'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
        404:
          description: ''
  /api/products/{id}/image:
    post:
      tags:
      - Products
      operationId: Products_UploadProductImage
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: string
        404:
          description: ''
  /api/productCategories/{idOrPath}:
    get:
      tags:
      - ProductCategories
      operationId: ProductCategories_GetProductCategoryById
      parameters:
      - name: idOrPath
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCategory'
    put:
      tags:
      - ProductCategories
      operationId: ProductCategories_UpdateProductCategoryDetails
      parameters:
      - name: idOrPath
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductCategoryDetailsRequest'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
        404:
          description: ''
    delete:
      tags:
      - ProductCategories
      operationId: ProductCategories_DeleteProductCategory
      parameters:
      - name: idOrPath
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
        404:
          description: ''
  /api/productCategories:
    post:
      tags:
      - ProductCategories
      operationId: ProductCategories_CreateProductCategory
      requestBody:
        x-name: request
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductCategoryRequest'
        required: true
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCategory'
        400:
          description: ''
  /api/ProductCategories/api/productCategories:
    get:
      tags:
      - ProductCategories
      operationId: ProductCategories_GetProductsCategories
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          format: int32
        x-position: 1
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
        x-position: 2
      - name: searchTerm
        in: query
        schema:
          type: string
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResultOfProductCategory'
  /WeatherForecast:
    get:
      tags:
      - WeatherForecast
      operationId: WeatherForecast_Get
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
components:
  schemas:
    PagedResultOfProduct:
      type: object
      additionalProperties: false
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        total:
          type: integer
          format: int32
    Product:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/ProductCategoryParent'
        description:
          type: string
        price:
          type: number
          format: decimal
        regularPrice:
          type: number
          format: decimal
          nullable: true
        image:
          type: string
          nullable: true
        handle:
          type: string
    ProductCategoryParent:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
          nullable: true
        handle:
          type: string
        path:
          type: string
        parent:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/ProductCategoryParent'
    SortDirection:
      type: integer
      description: ''
      x-enumNames:
      - Desc
      - Asc
      enum:
      - 0
      - 1
    CreateProductRequest:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        description:
          type: string
        categoryId:
          type: integer
          format: int64
        price:
          type: number
          format: decimal
        handle:
          type: string
    UpdateProductDetailsRequest:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        description:
          type: string
    UpdateProductPriceRequest:
      type: object
      additionalProperties: false
      properties:
        price:
          type: number
          format: decimal
    UpdateProductHandleRequest:
      type: object
      additionalProperties: false
      properties:
        handle:
          type: string
    UpdateProductCategoryRequest:
      type: object
      additionalProperties: false
      properties:
        productCategoryId:
          type: integer
          format: int64
    ProductCategory:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
          nullable: true
        parent:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/ProductCategoryParent'
        canAddProducts:
          type: boolean
        productsCount:
          type: integer
          format: int64
        handle:
          type: string
        path:
          type: string
    CreateProductCategoryRequest:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        description:
          type: string
        parentCategoryId:
          type: integer
          format: int64
        handle:
          type: string
    UpdateProductCategoryDetailsRequest:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        description:
          type: string
    PagedResultOfProductCategory:
      type: object
      additionalProperties: false
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductCategory'
        total:
          type: integer
          format: int32
    WeatherForecast:
      type: object
      additionalProperties: false
      properties:
        date:
          type: string
          format: date-time
        temperatureC:
          type: integer
          format: int32
        summary:
          type: string
          nullable: true
        temperatureF:
          type: integer
          format: int32
