on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "src/Carts/Carts.API/**"
        
name: Build and deploy Carts.API
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        dockerfilePath: src/Carts/Carts.API/Dockerfile
        registryUrl: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registryUsername: ${{ secrets.REGISTRY_USERNAME }}
        registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
        containerAppName: yourbrand-carts-api
        resourceGroup: ${{ secrets.RESOURCE_GROUP }}
        location: 'Sweden Central'
        targetPort: 8080
